server:
  port: 8060

spring:
  application:
    name: spring-cloud-test-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#feign开启熔断器
feign:
  hystrix:
    enabled: true