server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: spring-cloud-test-service-admin